#pragma once

// Client needs to include windows.h or winioctl.h
// Driver needs to include ntddk.h or wdm.h

#define LOADERDEVICETYPE 0x8000
#define IOCTL_LOADER_LOAD_FROM_FILE CTL_CODE(LOADERDEVICETYPE, 0x800, METHOD_BUFFERED,	FILE_WRITE_ACCESS)
#define IOCTL_LOADER_UNLOAD			CTL_CODE(LOADERDEVICETYPE, 0x801, METHOD_NEITHER,	FILE_WRITE_ACCESS)
#define IOCTL_LOADER_EXEC			CTL_CODE(LOADERDEVICETYPE, 0x802, METHOD_NEITHER,	FILE_WRITE_ACCESS)